### ISSUE TITLE
Undefined method 'duplicate' after active_scaffold update

### ISSUE THREAD

**Issue by JoaoFelipe** [activescaffold/active_scaffold_duplicate#1]
After updating active_scaffold from 3.3.3 to 3.4.1, and rails from 3.2.18 to 3.2.19, I started to get an error on my controller:

```
undefined method `duplicate' for ReportConfigurationsController:Class (NoMethodError)
  /usr/local/sapos/computacao/staging/vendor/bundle/ruby/1.9.1/gems/active_scaffold-3.4.1/lib/active_scaffold/configurable.rb:24:in `rescue in method_missing'
  /usr/local/sapos/computacao/staging/vendor/bundle/ruby/1.9.1/gems/active_scaffold-3.4.1/lib/active_scaffold/configurable.rb:18:in `method_missing'
  /usr/local/sapos/computacao/staging/vendor/bundle/ruby/1.9.1/gems/active_scaffold-3.4.1/lib/active_scaffold/config/core.rb:219:in `method_missing'
  /usr/local/sapos/computacao/staging/app/controllers/report_configurations_controller.rb:13:in `block in <class:ReportConfigurationsController>'
  /usr/local/sapos/computacao/staging/vendor/bundle/ruby/1.9.1/gems/active_scaffold-3.4.1/lib/active_scaffold/configurable.rb:11:in `instance_exec'
  /usr/local/sapos/computacao/staging/vendor/bundle/ruby/1.9.1/gems/active_scaffold-3.4.1/lib/active_scaffold/configurable.rb:11:in `configure'
  /usr/local/sapos/computacao/staging/vendor/bundle/ruby/1.9.1/gems/active_scaffold-3.4.1/lib/active_scaffold/core.rb:86:in `active_scaffold'
  /usr/local/sapos/computacao/staging/vendor/bundle/ruby/1.9.1/gems/active_scaffold-3.4.1/lib/active_scaffold/bridges/cancan/cancan_bridge.rb:33:in `active_scaffold_with_cancan'
  /usr/local/sapos/computacao/staging/app/controllers/report_configurations_controller.rb:8:in `<class:ReportConfigurationsController>'
  /usr/local/sapos/computacao/staging/app/controllers/report_configurations_controller.rb:5:in `<top (required)>'
  /usr/local/sapos/computacao/staging/vendor/bundle/ruby/1.9.1/gems/activesupport-3.2.19/lib/active_support/dependencies.rb:251:in `require'
  /usr/local/sapos/computacao/staging/vendor/bundle/ruby/1.9.1/gems/activesupport-3.2.19/lib/active_support/dependencies.rb:251:in `block in require'
  /usr/local/sapos/computacao/staging/vendor/bundle/ruby/1.9.1/gems/activesupport-3.2.19/lib/active_support/dependencies.rb:236:in `load_dependency'
  /usr/local/sapos/computacao/staging/vendor/bundle/ruby/1.9.1/gems/activesupport-3.2.19/lib/active_support/dependencies.rb:251:in `require'
  /usr/local/sapos/computacao/staging/vendor/bundle/ruby/1.9.1/gems/activesupport-3.2.19/lib/active_support/dependencies.rb:359:in `require_or_load'
  /usr/local/sapos/computacao/staging/vendor/bundle/ruby/1.9.1/gems/activesupport-3.2.19/lib/active_support/dependencies.rb:313:in `depend_on'
  /usr/local/sapos/computacao/staging/vendor/bundle/ruby/1.9.1/gems/activesupport-3.2.19/lib/active_support/dependencies.rb:225:in `require_dependency'
  /usr/local/sapos/computacao/staging/vendor/bundle/ruby/1.9.1/gems/railties-3.2.19/lib/rails/engine.rb:444:in `block (2 levels) in eager_load!'
  /usr/local/sapos/computacao/staging/vendor/bundle/ruby/1.9.1/gems/railties-3.2.19/lib/rails/engine.rb:443:in `each'
  /usr/local/sapos/computacao/staging/vendor/bundle/ruby/1.9.1/gems/railties-3.2.19/lib/rails/engine.rb:443:in `block in eager_load!'
  /usr/local/sapos/computacao/staging/vendor/bundle/ruby/1.9.1/gems/railties-3.2.19/lib/rails/engine.rb:441:in `each'
  /usr/local/sapos/computacao/staging/vendor/bundle/ruby/1.9.1/gems/railties-3.2.19/lib/rails/engine.rb:441:in `eager_load!'
  /usr/local/sapos/computacao/staging/vendor/bundle/ruby/1.9.1/gems/railties-3.2.19/lib/rails/application/finisher.rb:53:in `block in <module:Finisher>'
  /usr/local/sapos/computacao/staging/vendor/bundle/ruby/1.9.1/gems/railties-3.2.19/lib/rails/initializable.rb:30:in `instance_exec'
  /usr/local/sapos/computacao/staging/vendor/bundle/ruby/1.9.1/gems/railties-3.2.19/lib/rails/initializable.rb:30:in `run'
  /usr/local/sapos/computacao/staging/vendor/bundle/ruby/1.9.1/gems/railties-3.2.19/lib/rails/initializable.rb:55:in `block in run_initializers'
  /usr/local/sapos/computacao/staging/vendor/bundle/ruby/1.9.1/gems/railties-3.2.19/lib/rails/initializable.rb:54:in `each'
  /usr/local/sapos/computacao/staging/vendor/bundle/ruby/1.9.1/gems/railties-3.2.19/lib/rails/initializable.rb:54:in `run_initializers'
  /usr/local/sapos/computacao/staging/vendor/bundle/ruby/1.9.1/gems/railties-3.2.19/lib/rails/application.rb:136:in `initialize!'
  /usr/local/sapos/computacao/staging/vendor/bundle/ruby/1.9.1/gems/railties-3.2.19/lib/rails/railtie/configurable.rb:30:in `method_missing'
  /usr/local/sapos/computacao/staging/config/environment.rb:8:in `<top (required)>'
  config.ru:3:in `require'
  config.ru:3:in `block in <main>'
  /usr/local/sapos/computacao/staging/vendor/bundle/ruby/1.9.1/gems/rack-1.4.5/lib/rack/builder.rb:51:in `instance_eval'
  /usr/local/sapos/computacao/staging/vendor/bundle/ruby/1.9.1/gems/rack-1.4.5/lib/rack/builder.rb:51:in `initialize'
  config.ru:1:in `new'
  config.ru:1:in `<main>'
  /var/lib/gems/1.9.1/gems/passenger-4.0.5/helper-scripts/rack-preloader.rb:82:in `eval'
  /var/lib/gems/1.9.1/gems/passenger-4.0.5/helper-scripts/rack-preloader.rb:82:in `preload_app'
  /var/lib/gems/1.9.1/gems/passenger-4.0.5/helper-scripts/rack-preloader.rb:127:in `<module:App>'
  /var/lib/gems/1.9.1/gems/passenger-4.0.5/helper-scripts/rack-preloader.rb:6:in `<module:PhusionPassenger>'
  /var/lib/gems/1.9.1/gems/passenger-4.0.5/helper-scripts/rack-preloader.rb:5:in `<main>'
```

I'm using the plain duplicate action. I just configured up to Step 2:
conf.actions << :duplicate
